### PR TITLE
Add ALE linter support

### PR DESCRIPTION
**Pull request by CyberTailor**
Check ebuilds asynchronously!

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks! I'm going to trust you on this and merge it without testing.

**Comment by mgorny** [comment]
Actually, could you add your signoff, please? This is a bit large-ish to be merged without.

**Comment by CyberTailor** [comment]
Done.

**Comment by floppym** [comment]
This appears to have broken `make install`.
```
% make PREFIX=/home/floppym/.config/nvim install
mkdir -p "/home/floppym/.config/nvim/ale_linters/"
mkdir -p "/home/floppym/.config/nvim/doc/"
mkdir -p "/home/floppym/.config/nvim/ftdetect/"
mkdir -p "/home/floppym/.config/nvim/ftplugin/"
mkdir -p "/home/floppym/.config/nvim/indent/"
mkdir -p "/home/floppym/.config/nvim/plugin/"
mkdir -p "/home/floppym/.config/nvim/syntax/"
mkdir -p "/home/floppym/.config/nvim/syntax_checkers/"
cp "ale/linters/ebuild" "/home/floppym/.config/nvim/ale/linters/ebuild"
cp: cannot stat 'ale/linters/ebuild': No such file or directory
make: *** [Makefile:30: install-file-ale_linters_ebuild] Error 1
```

**Comment by msva** [comment]
probably, can be fixed with changing "ale_linters" to "ale-linnters" or just "ale"

// I'll test when I'd have spare time

**Pull request closed without merging**
