### PR TITLE
Support more email addresses

### PR DESCRIPTION
**Pull request by CyberTailor**
I know all regular expressions for emails are suboptimal, but yeah.

### CODE REVIEW

**Comment by mgorny** [comment]
Any reason we can't use something simpler, like `<[^<>@]+@[^<>@.]+\.[^<>@]+>`?

**Comment by CyberTailor** [comment]
We can and we should, maybe.

**Comment by mgorny** [comment]
> Commit no. 0001 was not signed off by the author!

**Comment by CyberTailor** [comment]
Oops. Fixed

**Comment by mgorny** [comment]
Thanks for both PRs! I've pushed v9 now.

BTW if you're interested, having some other color for the date `(YYYY-MM-DD)` would also be cool.

**Comment by msva** [comment]
btw, IIRC, there is a restriction in email RFC, that localpart (before `@`) can only contain `[a-zA-Z0-9+-.]` or something like that (I mean, unlike domains, it, for example, can not (IIRC, again), contain non-ASCII characters (like unicode)) (Well, neither domains can, but thanks to punycode).

Although, yeah, I don't think we should really care about whether user specified address fully corresponds e-mail address spec, or not, and current behaviour, of "only catch most stupid errors" is ok, imho.

**Pull request closed without merging**
