### PR TITLE
make use and unuse highlights always green and red

### PR DESCRIPTION
**Pull request by heyitscassio**

### CODE REVIEW

**Comment by mgorny** [comment]
Copyright signoff, please? (GLEP 76)

**Comment by heyitscassio** [comment]
Sorry, i'm not too familiar with committing to the gentoo repos, Is this right?

**Comment by mgorny** [comment]
Yes, sure.

**Comment by msva** [comment]
btw, what was the purpose of that commit?
Also:
1) why exactly darkgreen and red colors?
2) colors here are only defined for `ctermfg`, but not for `guifg`...

// anyway:
1) it looks ugly in some color schemes
2) I think hardcode is evil (until there is major reason) and also against the gentoo philosophy spirit.


So, @robbat2 @mgorny @mrueg I'm about to revert that commit (expecially because it brakes **my** experience.
Any objections?

**Comment by mgorny** [comment]
Yes, I do have an objection. Improve it, not remove it.

**Comment by msva** [comment]
Previous state (of using `Special` and `Keyword`) was ideal (at least, for me).
So, I have no idea how can I "improve, not remove" in that case.
I just want to return it to the ideal state, at least, if no one explain me the reason of such hardcoding of ugly colors...

**Pull request closed without merging**
