### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by mgorny**
A few semi-relevant changes that bring gentoo-syntax to 2016.
- [x] minor bug fixes and enhancements
- [x] GLEP67 support
- [x] eclassdoc-friendly eclass template
- [x] nice EAPI=6 ebuild
- [x] updated keywords for EAPI=6 and some modern eclasses

### CODE REVIEW

**Comment by mgorny** [comment]
@radhermit !

**Comment by radhermit** [comment]
A lot of the function list updates would be unnecessary if I ever finished my eclass function list generator script to auto-populate gentoo-syntax, but that's been sitting around for a while. :smile: 

Also, instead of having static banned/deprecation lists, I'd rather dynamically do it based on the EAPI of the ebuild.

**Comment by mgorny** [comment]
I don't think auto-generation can cover deprecations properly.

I thought about that too — but then, we don't distinguish between deprecated and banned, and banning in a newer EAPI implicitly deprecates in earlier.

**Comment by radhermit** [comment]
Thanks, merged. I'll do the related work I was stalling on later.

**Pull request closed without merging**
