### PR TITLE
newmetadata: Include pypi upstream tag for Python packages

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/python

**Comment by radhermit** [comment]
I don't think all dev-python pkgs will have pypi pages and also pypi names can sometimes not match pkg names so I'm hesitant to add something that will result in possibly incorrect data being added by default.

**Comment by msva** [comment]
Maybe it is worth to make a call to `pip` to check if such package exists, and only add pip-upstream if so?

// or just close PR if not actual anymore?

**Comment by mgorny** [comment]
Heh, in the end I've done the same thing again x_x.

**Pull request closed without merging**
